### ISSUE TITLE
broad ideas for features 

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#10]
- [x] resize indivual grid plots or compositions of subplots within a canvas. Similar to Qt QSplitter
- [x] dynamically change controllers across subplots

**Comment by GarrettBlair** [comment]
Might be nice to be able to define separation between grid plots (x and y separation) and potentially the color of separator (white/black/red/etc.)

**Comment by GarrettBlair** [comment]
Rather than just a grid, a method for having multiple windows (so they can be positioned and resized separately) while still sharing the same controller. Similar to open cv windows perhaps.

**Comment by kushalkolar** [comment]
One idea which I've had is that a user can add rectangles to an empty canvas and resize/reshape those rectangles for where they want to create a subplot. Basically a controller than can move/resize entire scenes.

**Comment by kushalkolar** [comment]
"composing" subplots already possible with ipywidgets, see #2

**Comment by kushalkolar** [comment]
@GarrettBlair You can "manually" define various subplots and stack them together however you want using `HBox` and `VBox`, the last cell of the `simple.ipynb` example shows this: https://github.com/kushalkolar/fastplotlib/blob/master/examples/simple.ipynb
