### ISSUE TITLE
Histogram vmin vmax widget 

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#166]
pyqtgraph-like histograms that can be tied to an Image. We can make this very nice looking. In addition to a vertical line graphic to display the histogram, we can have a thick vertical on the side with colors set to the current cmap!

![image](https://github.com/kushalkolar/fastplotlib/assets/9403332/ff159200-b472-44a7-a0ae-9b999d89a44d)

**Comment by clewis7** [comment]
first step...fix histogram graphic lol

**Comment by kushalkolar** [comment]
No not necessary, just use a line

**Comment by kushalkolar** [comment]
Look at the pyqtgraph widget

**Comment by kushalkolar** [comment]
So now after #244 we can probably just use bidirectional link() between LinearRegionSelector of the HistogramLUTWidget and the image cmap vmin, vmax
