### ISSUE TITLE
GraphicFeatures refactor and improvements

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#182]
collection of current issues with `GraphicFeature`

- events info is becoming a bit of a mess and needs more consistency with information returned by events, #174 
- support selections of multiple indices for collections (like selecting multiple contours or temporal traces with Ctrl + click for example). This would also involve changes to `Interaction`
- #123 
- #132
- #101 
- #85 
- allow passing unique integers for color labels, useful for sklearn classifier outputs:
![image](https://user-images.githubusercontent.com/9403332/233283387-ad95615b-4c8c-45aa-a018-6ab50949cffa.png)

**Comment by kushalkolar** [comment]
@clewis7 I think we should think about `link()` and the `pick_info` a bit more.

Right now `link()` automatically works and just uses `new_data` between linked Graphics. If you want something more customized you can give link a `callback` kwarg.

I wonder if there's a better way to do this, and make it more generalizable so that `link()` can work with more `pick_info` keys than just `new_data`. For example, the best usecase of this is between `LinearRegionSelector` and `vmin` `vmax` of `ImageCmapFeature`.

How do we make a nice `link()` API?

Maybe we first add `"min"` and `"max"` to `LinearRegionSelector` `pick_info`, and then something like this:

```python
vmin_vmax_selector.link(
  "selection", 
  target=image_graphic,
  mapping={
      "selection.min": "cmap.vmin",   # map selection.min -> cmap.vmin
      "selection.max": "cmap.vmax",  # map selection.max -> cmap.vmax
  }
  bidirectional=True  # adds bidirectional link, calls `link()` but just with reversed mapping kwarg?
)
```

Needs more brainstorming :thinking: 

I wonder if there's a way to also simplify things like the euclidean function we use for mapping image -> contours.

**Comment by clewis7** [comment]
I feel like as far the euclidean function goes we could add a default `None` `mapping` arg to `link()` that could take values like ["euclidean", "emd", etc.]

**Comment by clewis7** [comment]
Oh I see, you are using mapping above to map changes between selection and cmap

**Comment by kushalkolar** [comment]
I just got another idea of how we could use link, make it not just between graphics but also widget classes?

```
# for exampline LinearSelector for time
time_selector.selection.link(
  "selection",
  target=image_widget,
  mapping={"selection": "current_index.t"},
  bidirectional=True
)
```

Would require making `current_index` a `@dataclass` probably, with dimensions as the attributes, and it would have to have event handlers in order to be bidirectional. Or maybe we allow bidirectional only for graphic features?

I think we could make it such that you can do `graphic.feature.link()`, and make it use something from the `pick_info` to set the attribute of any other arbitrary object.

The brainstorming continues...

**Comment by clewis7** [comment]
My initial thoughts are that I like this a lot, I think it will give us a lot more control with our interactivity and it would prevent us from having to make tons of event_handler functions

For instance, if this were possible, I would not need to have an event handler func to link my ethogram linear selector to the time dim `IntSlider` in my iw

**Comment by clewis7** [comment]
The only thing I think we are missing is how to address more complicated mappings that we might have without passing a callback func in the link step
