### ISSUE TITLE
sync subsets of controllers in `GridPlot` using subplot names

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#218]
idea from @ArjunPutcha

**Comment by ArjunPutcha** [comment]
Do you think this is something that should only be done upon initialization of gridplot, or should be a mutable feature after initialization?

**Comment by ArjunPutcha** [comment]
If we should only define this on initialization, do you think the following way is intuitive:
grid_plot = GridPlot(shape=(1,3), names = ['red', 'ir', 'violet'], controllers=['violet'])

Where passing in an array of strings automatically defines unique controllers only for those subplots?

Or if it can be modified after initialization, something like:
gridplot.sync_controllers(names = [])

**Comment by kushalkolar** [comment]
Making it mutable would be nice!

**Comment by kushalkolar** [comment]
Maybe giving a list of lists, where the plots that correspond to each sub-list are synced, example:

```python
gridplot = GridPlot(
  ..., 
  names=["red", "ir", "violet", "gamma"],
  controllers=[["red", "ir"], ["violet", "gamma"]]
)
```
