### ISSUE TITLE
Quick plot API proposal

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#227]
So I guess I'm really getting lazy now, but sometimes I think it would be nice to have 1 liners to plot things just like matplotlib. Sometimes when I'm in a rush to just check one image or one line I still use matplotlib because it takes 1 line instead of 3, and then I wish I had just done a fpl plot.

So API idea is something like:

```python
from fastplotlib.quick import plot, gridplot

plot.add_image(args)
plot.add_line()
# call show() automatically when the jupyter cell is executed
```

Also allow:

```python
from fastplotlib.quick import plot, gridplot

plot.add_image()
plot.add_scatter()
plot.show()

plot.add_image()
plot.show()
# VBox the outputs
```

**Comment by kushalkolar** [comment]
I think this is what we need to make this possible! https://ipython.readthedocs.io/en/stable/config/callbacks.html#post-run-cell

**Comment by kushalkolar** [comment]
Do we _really_ want to do this? @clewis7

**Comment by clewis7** [comment]
I don't think so
