### ISSUE TITLE
sprint goals

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#240]
meta issue of sprint goals

- [x] #197 
- [ ] #166 
- [x] #157 
- [x] #132 
- [x] refactor and write tests for #241, the cmap_values parsing code is messy right now
- [x] fix broadcasting errors when changing data in ImageWidget to different shape
- [x] more camera and controller options, `pygfx` has many more options now, like `FlyController`
- [ ] Nicer readme with more epic visualizations, ideas from #9

**Comment by clewis7** [comment]
- [ ] fix broadcasting errors when changing data in `ImageWidget` to different shape
