### ISSUE TITLE
ImageWidget with mixed ndim

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#255]
This is starting to annoy me in `mesmerize-viz`, can't have mixed ndim so I made a bunch of sphaghetti to deal with it because I can't just use the new `set_data()`

Ideas for how to deal with mixed number of dimensions:
1. Last two dims are always the 2D image dimensions, [x, y]
2. We make a slider for every other dim
3. If an image doesn't have a slider for that dim, it's ignored when that slider moves, or if that dim is used in a window function, or apply function etc.

**Comment by clewis7** [comment]
I think this seems logical, but then for set_data() would we allow setting data with different dims?

**Comment by kushalkolar** [comment]
I think at this point we should allow that, add a new slider if necessary for a new dim?

**Comment by kushalkolar** [comment]
I say we officially wait for napari-lite and not implement this in the scope of fastplotlib?
