### ISSUE TITLE
Usage with glfw - imgui

### ISSUE THREAD

**Issue by mbignotti** [fastplotlib/fastplotlib#260]
Hi!
Are there any examples about the usage with `glfw`?
I'm trying to understand if I can use `fastplotlib` with https://github.com/pthom/imgui_bundle (that relies on `glfw`).

Thanks a lot!

**Comment by kushalkolar** [comment]
Hi! Thanks for your interest! I am also interested integrating this with `imgui`, see this recent dicussion: https://github.com/pyimgui/pyimgui/issues/336

I just pushed a new release which contains a small fix to make the minimal install work: https://github.com/kushalkolar/fastplotlib#minimal-use-with-your-own-qt-or-glfw-applications

You will need to `pip install glfw` in addition to that.

For examples, use any of the test examples and give the kwarg `canvas="glfw"` when constructing a `Plot` or `GridPlot` to force `glfw`. You will also need to add  `from fastplotlib import run`, and call `run()` at the end.

Test examples are within most of these subdirs (image, line, line_collection, scatter): https://github.com/kushalkolar/fastplotlib/tree/master/examples

For examples with `image_simple.py`: https://github.com/kushalkolar/fastplotlib/blob/master/examples/image/image_simple.py

```python
from fastplotlib import Plot, run
import numpy as np
import imageio.v3 as iio

# these two lines from the example file are not required
# from wgpu.gui.offscreen import WgpuCanvas
# from pygfx import WgpuRenderer

# force glfw
plot = Plot(canvas="glfw")

data = iio.imread("imageio:camera.png")

# plot the image data
image_graphic = plot.add_image(data=data, name="iio camera")

plot.show()

plot.canvas.set_logical_size(800, 800)

plot.auto_scale()

# show and run
plot.show()
run()
```

You can also use the example notebooks and pass `canvas="glfw"` to `Plot` or `GridPlot` and it will use the glfw canvas without blocking notebook executation.

**Comment by mbignotti** [comment]
Hi @kushalkolar!
Thanks a lot for your answer! 
Your example works fine!
I'll let you know if I manage to make it work with `imgui-bundle`, which is a batteries-included version of `pyimgui`.

Thank you!

**Comment by kushalkolar** [comment]
My guess is that imgui integration would probably be done with [`wgpu-py`](https://github.com/pygfx/wgpu-py) and [`pygfx`](https://github.com/pygfx/pygfx), since `fastplotlib` is built on top of [`pygfx`](https://github.com/pygfx/pygfx).

See related discussion: https://github.com/pyimgui/pyimgui/issues/336

I don't have experience with imgui, very interested to see what you find out!

**Comment by kushalkolar** [comment]
@mbignotti wondering if you were able to try this out?

**Comment by mbignotti** [comment]
Hey @kushalkolar, 
I'm really sorry, but I stopped working on the imgui project a few weeks after I opened this issue and I totally forgot to reply here. My apologies!
Unfortunately I haven't had the chance to try it out. The original idea was trying to mimic what is being done in this fantastic [series](https://www.youtube.com/watch?v=gfW1Fhd9u9Q&list=PLlrATfBNZ98edc5GshdBtREv5asFW3yXl) (at a much simpler level, of course), but with numpy, numba and imgui. Then I thought I could try use fastplotlib to display the image in real time.
Unfortunately, other priorities had arrived in the mean time, and I abandoned the project. Sorry again.

**Comment by kushalkolar** [comment]
Thanks for the update! Creating viewports/subplots in a drag-drop-resize fashion would be really cool. I might just try and learn ImGUI soon and try to do it myself, but it has been years since I've touched C++ and my C++ abilities are very basic.

**Comment by mbignotti** [comment]
I don't think that using C++ is necessary here. The python bindings provide the same functionalities. However, I don't know if fastplotlib can be used to display an image inside an imgui window.

**Comment by kushalkolar** [comment]
Hi, this is finally being worked on in #571
