### ISSUE TITLE
Modes for selector `Sychronizer` and use of arrow key

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#262]
Right now the `Synchronizer` for selctors seems to work for pointer events. 

- [ ] make it work for arrow key events too, so that we can sync selectors between different renderers (and therefore different plot areas)
- [ ] have two modes
  - [ ] one where it just sychronizes the deltas (this is how it is currently implemented) but Selectors can all be in different positions. 
  - [ ] another mode where it sychronizes the absolute position of the selectors, this is useful for moving things in sync across different renders (i.e. different plot areas)

**Comment by clewis7** [comment]
I think this is a good idea and would have a lot of use cases (i.e. animal soup ethogram comparisons lol)

What would be the default though? Syncing with deltas or absolute position, I feel like the latter is more desirable and reflects "syncing" behavior better

**Comment by kushalkolar** [comment]
put this on hold until https://github.com/pygfx/pygfx/pull/665 and https://github.com/fastplotlib/fastplotlib/pull/413

**Comment by kushalkolar** [comment]
synchronizer will be removed in #473 , so I'm closing this. This should be handled in higher level libs.
