### ISSUE TITLE
Issue with add_text() - unable to set position

### ISSUE THREAD

**Issue by tomomano** [fastplotlib/fastplotlib#295]
I was using `Plot` object's `add_text()` method to overlay a text on images.
`add_text()` do not seem to treat the argument `position` correctly. The texts are always diplayed at (0,0,2).

Code
```
import fastplotlib as fpl
import numpy as np

plot = fpl.Plot()
plot.add_image(np.random.randn(300,300))
t = plot.add_text("Hello", position=(50,50,0))
plot.show()
```

This should place the text at (50,50,0), but it does not. The screenshot below is what I got.
![image](https://github.com/fastplotlib/fastplotlib/assets/31726174/3629c120-790f-4115-a4b5-2a97095be7d6)

I attempted to use `update_position()` method of the TextGraphics object. This throws an following error.

```
t.update_position((100,100,100))

AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 t.update_position((100,100,100))

File /usr/local/lib/python3.10/dist-packages/fastplotlib/graphics/text.py:68, in TextGraphic.update_position(self, pos)
     67 def update_position(self, pos: Tuple[int, int, int]):
---> 68     self.world_object.position.set(*pos)

AttributeError: 'tuple' object has no attribute 'set'
```

I can force to update the position by directly accessing the propety though:

```
t.position_x = 100
t.position_y = 200
```

This approach works, but I think this is not how the API was designed.

**Comment by kushalkolar** [comment]
Hi, thanks for your interest in fastplotlib! The state of text is currently primitive and we haven't, fully thought of the API for text, it is in #55 and we hope to have proper text by early next year. The way that you're currently setting text is correct using the "position_" properties, since it just inherited from `Graphic`.

If you have any ideas or suggestions for the text API let us know. :)

**Comment by tomomano** [comment]
OK, thanks for sharing the information. I'll use this function in a rather hacky way.
But I thought that `add_text` would be very useful, for example when overlaying contour and its neuron ID, so one can quickly relate the spatial location of the neuron and its ID.
I think the current API design is good, it aligns with our familiar matplotlib's `text()` API.

**Comment by kushalkolar** [comment]
Yes I agree text is important, we just have a lot of other things on our plate as well.
