### ISSUE TITLE
Function book

### ISSUE THREAD

**Issue by zhouyi0812** [fastplotlib/fastplotlib#296]
Hello,

I wonder do you have function book available online? I am plot the heat map trying to add the x/y axis, but I try many common way and it doesn't work. 

Thank you!

**Comment by clewis7** [comment]
Hi! 

I would recommend taking a look at our [docs](https://fastplotlib.readthedocs.io/en/latest/index.html), in particular here are the docs for the[ `HeatmapGraphic`](https://fastplotlib.readthedocs.io/en/latest/api/graphics/HeatmapGraphic.html).

The kwargs `position_x`, `position_y`, and `position_z` correspond to the respective axis position, these can be set by passing `float` values when instantiating the graphic. 

@zhouyi0812 Is this what you are referring to?

**Comment by zhouyi0812** [comment]
Hello! 

Thank you for sharing!
Hmm, I mean how to label the x/y axis.

I have tried: plot.add_xlabel and something similar but looks did not work.
Thank you for your help!

<img width="731" alt="Screen Shot 2023-07-21 at 12 16 50 PM" src="https://github.com/fastplotlib/fastplotlib/assets/48576330/42efcd61-6748-4027-9277-126a5a414b76">

**Comment by clewis7** [comment]
Yes, I see what you are saying now. We do not currently support axes labels. We are still waiting for some developments with pygfx before implementing. You can play with the `TextGraphic` manually if you want. 

Also it looks like your toolbar is not rendering properly. If you are using Jupyter Notebook I recommend switching to Jupyter Lab instead!

**Comment by kushalkolar** [comment]
closing, @zhouyi0812 feel free to re-open if you have more questions or open another issue.
