### ISSUE TITLE
autoconnect existing ipywidgets to selections 

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#297]
Came up while helping Minel on her use cases, instead of manually connecting an ipywidget's `observe`, we could make it simpler by providing a `add_ipywidget_handler(<ipywidget_instance>)` that links the ipywidget and `Selector`. 

Thoughts:
- should this be bidirectional? I think yes, any caveats (recurusion etc.?)
- `LinearSelector` is compatible with `IntSlider` and `FloatSlider`, `FloatLogSlider`
- `LinearRegionSelector` is compatible with `IntRangeSlider` and `FloatRangeSlider` 
- I don't think it makes sense for `RectangleRegionSelector` to be connectable to any corresponding `ipywidget`?

@clewis7 thoughts?

**Comment by clewis7** [comment]
I think this sounds fine, perhaps there would be issues with recursion if bidirectional when handling events

Just to clarify you are saying if you added a linear selector to a plot and then wanted to connect to a ipywidget to the selector to have a general method for connecting the linear selector to the ipywidget? 

I am struggling to think of the use case, what was Minel trying to do?

**Comment by minel-arinel** [comment]
I have an ImageWidget with a calcium imaging recording and a line collection of contours plotted on top. I also have a separate Plot that shows the line graph of temporal responses of a clicked cell on the ImageWidget. On the Plot, I want to add a LinearSelector to mark as a time point of the ImageWidget. So basically just being able to slide that LinearSelector left-right on the temporal Plot as the ImageWidget 't' slider is changing.

**Comment by kushalkolar** [comment]
@minel-arinel after #298 you can just do:

```python
selector.add_ipywidget_handler(iw.sliders["t"])
```

**Comment by kushalkolar** [comment]
@minel-arinel #298 is now merged
