### ISSUE TITLE
make `jupyterlab-sidecar` a nb dependency?

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#299]
@clewis7 they are now on jupyterlab v4, thoughts? It will make the demo nbs nicer.

https://github.com/jupyter-widgets/jupyterlab-sidecar

**Comment by clewis7** [comment]
I think it is super useful for demos and in general when you are prototyping and don't want to have to keep scrolling up to the plot

**Comment by clewis7** [comment]
but this does not mean we are making jupyterlab v4 pinned right?

**Comment by kushalkolar** [comment]
yes we should pin v4, I wonder if the nb tests work with v4 too.

**Comment by kushalkolar** [comment]
as discussed on slack, pinning >=4 is not necessary since `sidecar` also works on v3
