### ISSUE TITLE
make `sidecar=False` the default?

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#342]
@clewis7 @EricThomson your thoughts would be great. Most libraries put plotting outputs right after the cell so maybe we should follow that as the default? It also avoids things like this: https://github.com/fastplotlib/fastplotlib/issues/337

**Comment by EricThomson** [comment]
Yes this seems right people will be confused otherwise I think.

**Comment by kushalkolar** [comment]
@clewis7 I'll do this in #313
