### ISSUE TITLE
Unexpected Argument: 'vmin_vmax_sliders'

### ISSUE THREAD

**Issue by brian1000** [fastplotlib/fastplotlib#375]
Hello. I wanted to try the interactivity notebook from your scipy2023 talk linked [here](https://github.com/fastplotlib/fastplotlib-scipy2023/blob/master/interactivity.ipynb). Everything went alright except for the pieces of code that mentioned the vmin_vmax_slider of the ImageWidget, i.e. 
```
# for the image data and contours
cnmf_iw = fpl.ImageWidget(
    movie, 
    vmin_vmax_sliders=True, 
    grid_plot_kwargs={"size": (600, 400)},
    cmap="gnuplot2",
)
```
and `cnmf_iw.vmin_vmax_sliders[0].value = (-5, 15)`. I am not familiar with the fastplotlib library so I imagine some of the things changed since then. Could you please help me make the sliders work in the current version of fastplotlib or point me to the version that worked for this example? 
This is the error I get: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[9], line 2
      1 # for the image data and contours
----> 2 cnmf_iw = fpl.ImageWidget(
      3     movie, 
      4     vmin_vmax_sliders=True, 
      5     grid_plot_kwargs={"size": (600, 400)},
      6     cmap="gnuplot2",
      7 )
      9 # temporal plot
     10 plot_temporal = fpl.Plot(size=(600,100))

File ~\anaconda3\envs\Ca2\lib\site-packages\fastplotlib\widgets\image.py:558, in ImageWidget.__init__(self, data, dims_order, slider_dims, window_funcs, frame_apply, grid_shape, names, grid_plot_kwargs, histogram_widget, **kwargs)
    556 frame = self._process_indices(d, slice_indices=self._current_index)
    557 frame = self._process_frame_apply(frame, data_ix)
--> 558 ig = ImageGraphic(frame, name="image_widget_managed", **kwargs)
    559 subplot.add_graphic(ig)
    560 subplot.name = name

File ~\anaconda3\envs\Ca2\lib\site-packages\fastplotlib\graphics\image.py:259, in ImageGraphic.__init__(self, data, vmin, vmax, cmap, filter, isolated_buffer, *args, **kwargs)
    201 def __init__(
    202     self,
    203     data: Any,
   (...)
    210     **kwargs,
    211 ):
    212     """
    213     Create an Image Graphic
    214 
   (...)
    256 
    257     """
--> 259     super().__init__(*args, **kwargs)
    261     data = to_gpu_supported_dtype(data)
    263     # TODO: we need to organize and do this better

TypeError: __init__() got an unexpected keyword argument 'vmin_vmax_sliders'
```

I'm currently working with the pip installation of fastplotlib[notebook] (v01.0a15) on windows 10 in jupyter lab. I'm using the demo data provided in the scipy2023 repo from which this ipynb originates. Thanks a lot!

**Comment by kushalkolar** [comment]
Hi, thanks for posting an issue! The vmin vmax sliders have been replaced by a histogram widget in #344. You can just remove that kwarg, the histogram tool is made automatically.

**Comment by brian1000** [comment]
Hello @kushalkolar, thanks for the prompt response! If I may add to this ~ we should probably change this issue to simply running the interactivity notebook. I also have an issue with the **Interacitvity of Graphics using link() and callback functions** section. After running the following code, I try to click on parts of the video ~ but I get an error. This is the code
```
# link image to contours
image_graphic = cnmf_iw.gridplot[0,0]["image_widget_managed"]

image_graphic.link(
    "click",
    target=contours_graphic,
    feature="colors", 
    new_data="cyan", 
    callback=euclidean
)

# a vertical line that is syncronized to the image widget "t" (timepoint) slider
def update_timepoint(ev):
    ix = ev.pick_info["selected_index"]
    cnmf_iw.sliders["t"].value = ix


# callback function to display correct temporal trace
def generate_temporal(ev):
    # clear the plot 
    plot_temporal.clear()
    
    # get data of selected ix
    data = temporal[ev.pick_info["collection-index"]]
    
    # add trace to plot 
    temporal_graphic = plot_temporal.add_line(data, colors="magenta")
    
    # add selector synced to "t" slider
    selector = temporal_graphic.add_linear_selector()
    selector.selection.add_event_handler(update_timepoint)
    
    plot_temporal.auto_scale()

# add event handler so that temporal trace is generated when contour is clicked on
contours_graphic[:].colors.add_event_handler(generate_temporal)

# thickness of contour
contours_graphic.link("colors", target=contours_graphic, feature="thickness", new_data=5)
```
and this is the error: 
```
Error during handling click event
Traceback (most recent call last):
  File "C:\Users\emricklab\anaconda3\envs\Ca2\lib\site-packages\wgpu\gui\base.py", line 24, in log_exception
    yield
  File "C:\Users\emricklab\anaconda3\envs\Ca2\lib\site-packages\pygfx\objects\_events.py", line 395, in handle_event
    callback(event)
  File "C:\Users\emricklab\anaconda3\envs\Ca2\lib\site-packages\fastplotlib\graphics\_base.py", line 302, in _event_handler
    target_info.callback_function(
  File "C:\Users\emricklab\AppData\Local\Temp\ipykernel_864\2412634740.py", line 18, in euclidean
    target._set_feature(feature="colors", new_data=new_data, indices=ix)
AttributeError: 'LineCollection' object has no attribute '_set_feature'
```
I get a subsequent error on each click event, and no contours are highlighted. The vbar that's supposed to update on top of the trace also isn't there.

**Comment by kushalkolar** [comment]
We made set_feature public recently, so you can remove the underscore.

**Comment by brian1000** [comment]
Thank you very much @kushalkolar for getting me started I really appreciate it. Everything works as intended.

**Comment by kushalkolar** [comment]
This is a more up to date neuro example that also uses pynapple to sync behavior and physiology data. Note that the datasets aren't included because they're 30GB, but you can probably get the general idea of how to use the API: https://github.com/fastplotlib/fastplotlib-sfn2023/blob/main/neuro_demo.ipynb

**Comment by brian1000** [comment]
This is great, I will study the neuro_demo notebook in the future. Sad I missed you all at SfN : D Thanks for the great work!

**Comment by kushalkolar** [comment]
closing this, feel free to open another issue if you have more questions/issues.
