### ISSUE TITLE
Problems with `WgpuRenderer` when running on a cloud instance

### ISSUE THREAD

**Issue by jsiegle** [fastplotlib/fastplotlib#376]
I am trying to use `fastplotlib` in the cloud (a use case I'm sure many others are interested in as well). However, with my current configuration, I'm not able to execute any of the demos.

I'm using Code Ocean, which runs JupyterLab on Linux inside a Docker container on an AWS EC2 instance with a GPU.

I cloned the latest `fastplotlib` code from GitHub and ran `pip install -e .[notebook]`

All of the demos fail when trying to create a `WgpuRenderer` object. This is the simplest example (based on `pygfx`) I can use to trigger the error:

```python
import pygfx as gfx

cube = gfx.Mesh(
    gfx.box_geometry(200, 200, 200),
    gfx.MeshPhongMaterial(color="#336699"),
)

gfx.show(cube)
```

Here is the error message:

```
File /opt/conda/lib/python3.10/site-packages/pygfx/utils/show.py:168, in Display.show(self, object, up)
    165     from wgpu.gui.auto import WgpuCanvas
    167     self.canvas = WgpuCanvas()
--> 168     self.renderer = WgpuRenderer(self.canvas)
    169 elif self.renderer is not None:
    170     self.canvas = self.renderer.target

File /opt/conda/lib/python3.10/site-packages/pygfx/renderers/wgpu/_renderer.py:136, in WgpuRenderer.__init__(self, target, pixel_ratio, show_fps, blend_mode, sort_objects, enable_events, gamma_correction, *args, **kwargs)
    133 self.pixel_ratio = pixel_ratio
    135 # Make sure we have a shared object (the first renderer creates the instance)
--> 136 self._shared = get_shared()
    137 self._device = self._shared.device
    139 # Init counter to auto-clear

File /opt/conda/lib/python3.10/site-packages/pygfx/renderers/wgpu/_shared.py:146, in get_shared()
    141 """Get the globally shared instance. Creates it if it does not yet exist.
    142 This should not be called at the import time of any module.
    143 Use this to get the global device: `get_shared().device`.
    144 """
    145 if Shared._instance is None:
--> 146     Shared()
    147 return Shared._instance

File /opt/conda/lib/python3.10/site-packages/pygfx/renderers/wgpu/_shared.py:55, in Shared.__init__(self, canvas)
     50 Shared._instance = self
     52 # Create adapter and device objects - there should be just one per
     53 # process. Having a global device provides the benefit that we can draw
     54 # any object anywhere.
---> 55 self._adapter = wgpu.gpu.request_adapter(power_preference="high-performance")
     56 self._device = self.adapter.request_device(
     57     required_features=list(Shared._features), required_limits={}
     58 )
     60 # Create a uniform buffer for std info
     61 # Stored on _store so if we'd ever swap it out for another buffer,
     62 # the pipeline automatically update.

File /opt/conda/lib/python3.10/site-packages/wgpu/base.py:100, in GPU.request_adapter(self, power_preference, force_fallback_adapter, canvas)
     97 # If this method gets called, no backend has been loaded yet, let's do that now!
     98 from .backends.auto import gpu  # noqa
--> 100 return gpu.request_adapter(
    101     power_preference=power_preference,
    102     force_fallback_adapter=force_fallback_adapter,
    103     canvas=canvas,
    104 )

File /opt/conda/lib/python3.10/site-packages/wgpu/backends/wgpu_native/_api.py:255, in GPU.request_adapter(self, power_preference, force_fallback_adapter, canvas)
    253 if adapter_id is None:  # pragma: no cover
    254     error_msg = error_msg or "Could not obtain new adapter id."
--> 255     raise RuntimeError(error_msg)
    257 return self._create_adapter(adapter_id)

RuntimeError: Request adapter failed (1): Validation Error

Caused by:
    No suitable adapter found
```

If I request a dedicated machine, I get the same error.

If there is no GPU on the instance, the error is different:

```
File /opt/conda/lib/python3.9/site-packages/pygfx/utils/show.py:168, in Display.show(self, object, up)
    165     from wgpu.gui.auto import WgpuCanvas
    167     self.canvas = WgpuCanvas()
--> 168     self.renderer = WgpuRenderer(self.canvas)
    169 elif self.renderer is not None:
    170     self.canvas = self.renderer.target

File /opt/conda/lib/python3.9/site-packages/pygfx/renderers/wgpu/_renderer.py:137, in WgpuRenderer.__init__(self, target, pixel_ratio, show_fps, blend_mode, sort_objects, enable_events, gamma_correction, *args, **kwargs)
    135 # Make sure we have a shared object (the first renderer creates the instance)
    136 self._shared = get_shared()
--> 137 self._device = self._shared.device
    139 # Init counter to auto-clear
    140 self._renders_since_last_flush = 0

File /opt/conda/lib/python3.9/site-packages/pygfx/renderers/wgpu/_shared.py:92, in Shared.device(self)
     89 @property
     90 def device(self):
     91     """The shared WGPU device object."""
---> 92     return self._device

AttributeError: 'Shared' object has no attribute '_device'
```

Let me know if this offers any clues as to what's going on. It would be helpful to know if the same errors occur on other cloud platforms (e.g. AWS Sagemaker, Google Colab), but I haven't tested those yet.

Thanks for your help trying to track down the issue!

**Comment by kushalkolar** [comment]
Thanks for posting the issue! This looks like it can't find a GPU. Are nvidia drivers installed in the docker container? Have you explicitly given the container access to the GPU? Can you run `nvidia-smi` (assuming you're using an nvidia GPU) within the container and print the output?

**Comment by jsiegle** [comment]
The container includes CUDA support, so NVIDIA drivers are available. Here's the output of `nvidia-smi`:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   19C    P8    12W /  70W |      2MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by kushalkolar** [comment]
Is the vulkan icd loader present, what does this give you:

```
cat /etc/vulkan/icd.d/nvidia_icd.json
```

If that doesn't work, what is in the `/etc/vulkan/icd.d/` dir? 

Since the Tesla T4 doesn't have a display output I wonder if something extra might be necessary.

I've never used code ocean or AWS, if you know a tutorial on how to run a docker container with jupyterlab on code ocean I can try this out myself.

**Comment by kushalkolar** [comment]
I would also try adding these to apt installs for building the container: 

```
sudo apt install libvulkan1 vulkan-utils
```

**Comment by jsiegle** [comment]
Here's the output of `cat /etc/vulkan/icd.d/nvidia_icd.json`:

```json
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.224"
    }
}
```

I tried installing `libvulkan1` and `vulkan-tools`, but it didn't help.

Code Ocean is [free with an academic email address](https://codeocean.com/signup), once you sign up it should be easy to create a capsule with JupyterLab and run some tests. Not 100% sure they have GPU instances for free accounts, though.

**Comment by kushalkolar** [comment]
I've been investigating this in detail. It seems like we're missing something that is required to run Vulkan applications  from the nvidia-cuda docker container. We're trying to figure out exactly what packages and other configuration details are necessary to allow both nvidia cuda compute and graphics to function within a docker container. We will post an example once we figure it out!

**Comment by jsiegle** [comment]
Thanks for the update, sounds like good progress!

**Comment by Di-Wang-AIND** [comment]
Any update on it? I am super interested in using `fastplotlib` in code ocean. Thanks!

> I've been investigating this in detail. It seems like we're missing something that is required to run Vulkan applications from the nvidia-cuda docker container. We're trying to figure out exactly what packages and other configuration details are necessary to allow both nvidia cuda compute and graphics to function within a docker container. We will post an example once we figure it out!

**Comment by kushalkolar** [comment]
@Di-Wang-AIND thanks for your interest, we'll post here once we get it working. We've got a lot on our plate right now so we try the docker once every few weeks. If you'd like to try it out and report what you get that'd be helpful :)

**Comment by kushalkolar** [comment]
@Di-Wang-AIND @jsiegle We'll have a lot more time to look into this in a few weeks, do one of you want to get on a call sometime after May 8? We've gotten it working on the Flatiron 
cluster and it mostly seems to be a matter of having all the system graphics libs installed.

**Comment by kushalkolar** [comment]
ok I figured this out quite quickly :laughing: , @Di-Wang-AIND @jsiegle followup in https://github.com/pygfx/wgpu-py/issues/493

**Comment by kushalkolar** [comment]
@jsiegle @Di-Wang-AIND

Just note that `fastplotlib` will undergo a lot of changes over the coming months (adding axes, selection tools, a refactor of the events system, etc.) so we recommend cloning the repo and installing in editable mode if you're working on neuroviz (I see https://github.com/neuroinformatics-unit/movement/issues/164 linked here). We have an internal project where we're working on building a general abstraction layer for neuroviz, there's potential to collaborate if you're interested.

**Comment by kushalkolar** [comment]
@jsiegle @Di-Wang-AIND @niksirbi

There might be potential to collaborate here, contact me if you're interested:

kkolar@flatironinstitute.org
