### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by apasarkar** [fastplotlib/fastplotlib#396]
The instructions tell us to install (1) mesa-vulkan-drivers and (2) libjpeg-turbo. On an Ubuntu 20.04 system, I was unable to find libjpeg-turbo. 

This Dockerfile (https://github.com/hantman-lab/animal-soup/blob/main/Dockerfile) suggests to install libturbojpeg0-dev; should we do this instead?

**Comment by kushalkolar** [comment]
That might be the Debian package name, Ubuntu varies slightly sometimes. Since we can't reliably provide the name for all distros and versions you'll have to search for variants of "libjpeg*" and "turbolibjpeg*", tab completion with apt should help :)
