### ISSUE TITLE
Local git clone not working (Mac Arm)

### ISSUE THREAD

**Issue by JohnStout** [fastplotlib/fastplotlib#399]
Trying to work through some notebooks on my Mac machine (M2 chip) to generate my own visualizations with fastplotlib. Here is the error:

      Cloning into 'fastplotlib'...
      remote: Enumerating objects: 4240, done.
      remote: Counting objects: 100% (1171/1171), done.
      remote: Compressing objects: 100% (509/509), done.
      remote: Total 4240 (delta 839), reused 825 (delta 656), pack-reused 3069
      Receiving objects: 100% (4240/4240), 19.24 MiB | 22.19 MiB/s, done.
      Resolving deltas: 100% (2598/2598), done.
      git-lfs filter-process: git-lfs: command not found
      fatal: the remote end hung up unexpectedly
      warning: Clone succeeded, but checkout failed.

This leaves a half baked fastplotlib folder. Any thoughts?

<img width="565" alt="Screenshot 2024-02-09 at 3 45 05 PM" src="https://github.com/fastplotlib/fastplotlib/assets/46092030/9c6bf524-6ef2-4274-bdc2-cb49f9ed21ce">

Thanks Kushal!
-John

**Comment by kushalkolar** [comment]
You need to install git-lfs:

```
git-lfs filter-process: git-lfs: command not found
```

See the contributing section of readme if you're interested in dev install. Otherwise we recommend just installing the release via pip.

**Comment by JohnStout** [comment]
Well that was an easy fix, sorry about that Kushal!
