### ISSUE TITLE
Showing a list of fastplotlib ImageWidgets

### ISSUE THREAD

**Issue by JohnStout** [fastplotlib/fastplotlib#416]
Hey fpl team, I am wondering if there is a way to produce separate fpl plots in a for loop? For example,

    for i in range(len(fpl_movies)):  
        fpl_movies[i].show(sidecar=True)

where `fpl_movies` are a list of `ImageWidgets`

I have noticed that the `.show` method in Jupyter-lab requires separate cells to run. That is, I cannot run a `.show` method on two separate ImageWidgets in the same Jupyter-lab cell.

Thanks!
John

**Comment by kushalkolar** [comment]
They're all ipywidget Widget objects so you can use all the available
ipywidget layouting, vbox, hbox, grids etc. There's a HBox example in the
simple.ipynb.
