### ISSUE TITLE
Directly pass `Controller` instances to `GridPlot` 

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#425]
#382 brought in one regression, we can no longer directly pass a controller instance, this is useful for synchronizing across plots so we should bring it back. For now users can manually assign controller instances for subplots _after_ creating a `GridPlot`.

**Comment by kushalkolar** [comment]
@clewis7 What do you think of this solution, we allow a `controllers` kwarg which can be an iterable of controller instances. If supplied `controller_ids` and `controller_types` are ignored. This is useful for manually defining the controllers of every subplot.

**Comment by clewis7** [comment]
I agree, having this functionality is important. I think maybe it would get confusing to have another controllers kwarg if there is already `controller_ids` and `controller_types`, but perhaps we would just need good documentation for users. 

I do agree that directly passing controllers would supersede the other kwargs.
