### ISSUE TITLE
pin max pygfx version before next release

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#452]
before next release, maybe pin wgpu version too? @almarklein

**Comment by almarklein** [comment]
pygfx [pins wgpu to a range](https://github.com/pygfx/pygfx/blob/34b26aca888708a800d130b6c8054543deb19e4d/pygfx/__init__.py#L30), so maybe better to not pint wgpu to avoid version clashes. You could consider pinning to a minimum wgpu version, if we add something that's really needed.
