### ISSUE TITLE
`GridPlot` -> `Figure` as the only user-facing layout 

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#457]
Layouts currently has a lot of multiple inheritance, this is partly due to us having a separate `Plot` and `GridPlot` class. After meeting with Almar I propose:

1. New `Figure` class which merges `GridPlot`, `Frame` and `RecordMixin`. 
2. Remove `Plot` in favor of creating a `Figure` with shape `(1, 1)`, i.e. one subplot. We can have `shape=(1, 1)` as default for `Figure`

@almarklein Does this make it easier to have axes etc.? Anything else to add?

**Comment by almarklein** [comment]
After `Plot` is gone, you can rename `SubPlot` to `Plot` :) 

I'm not sure yet if anything else is needed to properly support Axes, but at the very least this will be a great start!
