### ISSUE TITLE
Move some things to a new "neurowidgets" library

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#461]
Classes to move to a new lib for neurowidgets, all in `fastplotlib.graphics._base`: `Interaction`. `CallbackData`, `PreviouslyModifiedData`

`set_feature` and `reset_feature` on all Graphics

@clewis7 anything else?

This will require us to modify mesviz or just pin mesviz to the older version of fastplotlib because Amol's stuff is probably going to superseed the usefulness of mesviz in the nearterm :upside_down_face:

**Comment by clewis7** [comment]
Would we want to host this neurowidgets library in the `fastplotlib` organization, or will we want this to be hosted somewhere else?

**Comment by kushalkolar** [comment]
Up to you, I'm fine with anywhere
