### ISSUE TITLE
print report

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#464]
Building upon `pygfx.renderers.print_wgpu_report`, provide:

* insert fpl version
* add a function onto `Frame` so the specifics of the GPU that a specific PlotArea is using can be returned

**Comment by almarklein** [comment]
Note that wgpu probably already prints fpl's version ;) 

https://github.com/pygfx/wgpu-py/blob/501ac82e19f90ae5c8b6b62e2848f642dba9e2ec/wgpu/_diagnostics.py#L470-L489

**Comment by kushalkolar** [comment]
done in #491
