### ISSUE TITLE
docs on what fastplotlib is

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#480]
notes from meeting with @apasarkar

* we should put a few bullet points on the readme that quickly explains what fpl allows you to do
  * rapid prototyping, realtime analysis
  * easy API
  * ship with depedent packages as a standalone distributable - ex: pyinstaller, etc. (this is a medium term goal right now)

* somewhere in the docs we should put a comparison with other libraries, pyqtgraph, vispy, napari, bokeh, matplotlib

**Comment by apasarkar** [comment]
I think rendering speed is also important, esp as a function of data size

**Comment by kushalkolar** [comment]
I think some points on what fastplotlib is not would also be useful

    * fastplotlib is not related to matplotlib in any way. These are two completely different libraries with their own APIs
        * the fastplotlib way of doing things is different from matplotlib since fastplotlib is an _interactive_ plotting library that runs on the GPU using WGPU. Nonetheless, we want fastplotlib to be easy to use and learn. Hint: bring in your numpy and array intuitions when using fastplotlib rather than any matplotlib intuitions. If you know how to manipulate numpy arrays, you already understand half of fastplotlib! :tada:  We recommend looking at our examples gallery. If you have any questions please do not hesitate posting an issue or dicussion forum post :smile: 
    * fastplotlib is not meant for creating static publication figures, there are other libraries that are well suited for this task

**Comment by clewis7** [comment]
I think we can add this to the fpl guide, maybe after the section `What is fastplotlib?` we can have `What fastplotlib is NOT`
