### ISSUE TITLE
sphinx breaking

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#492]
So a sphinx release 43 minutes ago broke main after it passed in #491 :upside_down_face: 

https://github.com/sphinx-doc/sphinx/releases

**Comment by kushalkolar** [comment]
sphinx fixed this with a new release

**Comment by almarklein** [comment]
We also had a problem with the new Sphinx and sphinx_image_gallery: https://github.com/pygfx/pygfx/pull/735

**Comment by kushalkolar** [comment]
yup sphinx has been doing many bugfix releases today https://github.com/sphinx-doc/sphinx/blob/master/CHANGES.rst
