### ISSUE TITLE
Qt UI small toolbar buttons on Mac

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#494]
Just saw this fix elsewhere, might work here:

```
QT_ENABLE_HIGHDPI_SCALING=1
```

@almarklein @gviejo

(anyways once we have in-canvas UI we can forget about all this...)

**Comment by almarklein** [comment]
IIUC that is not necessary anymore, we do [this](https://github.com/pygfx/wgpu-py/blob/12544872f178860e1b9d7fd4344818188da0c1c6/wgpu/gui/qt.py#L125) in wgpu.

I think the problem with the buttons is also a different one; they are not a factor two smaller, but more like 1 or 2 pixels.
