### ISSUE TITLE
Figure.export() ? 

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#504]
What do you think about an `Figure.export()` method. I'm not sure because `Figure.renderer.snapshot()` exists, and then users can use their preferred library for saving that RGBA array to an image. And if they want to deal with the alpha channel in a special way they can do that. But I often see people searching the docs for "save" and "save figure" . We can have a simple `Figure.export()` `imageio` that takes the snapshot and does stuff in a default way? Just saves it to an png, or a jpg by stripping the alpha channel?

**Comment by apasarkar** [comment]
I think we should support a "maximum quality" figure export of some kind. This can be useful if people want to demo results of a pipeline/exploratory data analysis to others.

Similar thoughts re: exporting a high-resolution video ("screen recording") for sharing with others. I know many people who would regularly use this, especially the video bit.

**Comment by almarklein** [comment]
Makes sense!

> I think we should support a "maximum quality" figure export of some kind. 

I thought about this. Could perhaps be an option in pygfx to render a frame with a higher pixel-ratio.
