### ISSUE TITLE
add "Guide" to docs

### ISSUE THREAD

**Issue by clewis7** [fastplotlib/fastplotlib#510]
I really like the [`pygfx` Guide](https://pygfx.com/stable/guide.html) section in their docs and think that we could do something similar:

- Installation
- What is `fastplotlib`
- How to use `fastplotlib`
- `Figure`
- `Graphics`
- `GraphicFeatures`
- `Selectors`
- `Events`
- `ImageWidget`
- Using `fastplotlib` in `jupyter`

Especially will all the changes in #473, would be nice to have a "map" that explains where everything fits into the package

**Comment by kushalkolar** [comment]
Yea this can replace the quickstart nb
