### ISSUE TITLE
expose HistogramLUT tool at top level?

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#539]
currently to get the histogram LUT tool to use it manually the import is: `from fastplotlib.widgets.histogram_lut import HistogramLUT`. Let's expose this at top level, hopefully will be stable in a few months. And it's really not a widget but a "tool", maybe we should a new subpackage for tools?

@clewis7 @apasarkar thoughts?

**Comment by clewis7** [comment]
I think if you do subpackage for tools that you would also need to move selectors there…they are more of tools also

**Comment by kushalkolar** [comment]
Makes sense.

**Comment by apasarkar** [comment]
Agree with this idea, some related thoughts in #557

**Comment by kushalkolar** [comment]
> Hmm. Do we have some concrete situations where it is used on its own (i.e. without ImageWidget)? If so, then I think this idea makes sense. I've added some related thoughts in #557

yes I was doing it for some stuff where I needed more control that imagewidget gives :sweat_smile:

**Comment by kushalkolar** [comment]
this is already done in #571
