### ISSUE TITLE
interactive bar not fully shown.

### ISSUE THREAD

**Issue by chessdenman** [fastplotlib/fastplotlib#547]
HI, 
new to this library that seems to be completely what I need. 
However on my Mac M3 the interactive bar at the bottom of the window is getting chopped off.
Sorry to ask such a newby question but is there a fix for this?

I managed to interact with the picture by guessing the tiny area at the bottom of the screen had buttons on it

<img width="665" alt="Screenshot 2024-07-02 at 11 23 13" src="https://github.com/fastplotlib/fastplotlib/assets/21134453/d3925c1d-c993-4a7a-878c-20c3d10ac134">

**Comment by kushalkolar** [comment]
Sorry for the late response, holiday in the US right now. This is a known issue #494 , we will be moving to imgui for the toolbar in the coming months so it will be fixed then. :)
