### ISSUE TITLE
Reorganize examples

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#564]
I think we should:

- [ ] remove all nb examples except for quickstart, test_gc, and for now imagewidget. Once we have imgui integration we can remove imagewidget as well and just have the quickstart notebook
- [ ] move `examples/desktop` to just `examples/` and have these as the main examples for everything, docs, tests, users, etc. Move any examples that are currently only in the notebook to here.

 @clewis7 thoughts? I think this will make everything easier to maintain, and easier for users too since there would only be one set of examples.

**Comment by clewis7** [comment]
I think so too, much easier to have many many examples

The version control with the notebooks is tedious anyway I think

**Comment by clewis7** [comment]
I think in the future it would also be nice to add sections of the gallery for domain-specific examples (neuro, astronomy, etc.)
