### ISSUE TITLE
reduce WGPU max texture limit for tests

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#610]
I think this should be possible, so that then we can verify that our tiling works correctly by using small arrays. @almarklein do you know how to do this? Can we for example set the texture limit as 128?

**Comment by almarklein** [comment]
We have `enable_wgpu_features`(https://docs.pygfx.org/stable/advanced_api.html). We can expose setting limits in a similar fashion, but this is not yet implemented.

**Comment by kushalkolar** [comment]
Thanks! So the limit also applies to the canvas size since that's basically a texture too. Might need to use something like 1024 for the tests, will see.

**Comment by almarklein** [comment]
> So the limit also applies to the canvas size since that's basically a texture too. 

Ah! Interesting!

**Comment by kushalkolar** [comment]
done in #571
