### ISSUE TITLE
New release after 0.2.0?

### ISSUE THREAD

**Issue by hmaarrfk** [fastplotlib/fastplotlib#614]
Hey all,

I'm trying to get your package on conda-forge, but I realize that you are pinned to pygfx 0.2.0 which is quite "old" ;)

With the breaking changes in pygfx, we've moved to pygfx 0.4.X and I'm hoping you can release a new version of fastplotlib so it can be co-installable with our internal code.

LMK

xref: Trying to get the package on conda-forge ;) 
https://github.com/conda-forge/staged-recipes/pull/27629

**Comment by kushalkolar** [comment]
Yes we plan to have a new release in a few weeks, we have a few PRs to
merge.
