### ISSUE TITLE
sphinx gallery has a memory leak

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#626]
It executes examples and things stick around in RAM, so if an example loads a 1GB video then that sticks around. Can figure this out later, for now we can display heavily subsampled things etc. in the galleries.

This might really become an issue when we want to make example galleries to include computer vision and other scientific examples. Maybe we can find a reliable lazy loader. 

@almarklein wondering if you guys ever ran into this issue?

**Comment by almarklein** [comment]
mmm I'm not sure. We don't have examples that are *that* large. IIUC what happens if you have two examples that load 1GB of data, you'd expect that after running the two examples, the allocated ram  by the process is at most 1GB, but it's now 2GB, right?

BTW some time ago we ran all examples in a new subprocess, which avoids these kinds of errors. But the overhead is quite substantial, which is why we moved to a single-process solution, making tests and gallery generation *a lot* faster. On the other hand, using subprocesses would make it possible to parallelize ... mmm 🤔

**Comment by kushalkolar** [comment]
> IIUC what happens if you have two examples that load 1GB of data, you'd expect that after running the two examples, the allocated ram by the process is at most 1GB, but it's now 2GB, right?

Yup it seems like this is what's happening when I build it locally, video examples for instance: https://fastplotlib.readthedocs.io/en/latest/_gallery/image_widget/image_widget_single_video.html#sphx-glr-gallery-image-widget-image-widget-single-video-py 

Right now we're subsampling but still coming up against a limit, maybe we'll move to some github actions based doc build system and use github pages. We eventually want to have larger examples. The build takes 1.5GB on my computer, but I guess there's overhead so it's maxing out the 7GB limit on rtd.

**Comment by almarklein** [comment]
Let's compare the different implementations:

* https://github.com/fastplotlib/fastplotlib/blob/main/examples/tests/test_examples.py
* https://github.com/pygfx/wgpu-py/blob/main/examples/tests/test_examples.py
* https://github.com/pygfx/pygfx/blob/main/examples/tests/test_examples.py

In wgpu-py we use `request.addfinalizer(unload_module)` to clear the module after the test. The pygfx version was updated some time ago, it uses a custom `import_from_path()` function that does not add the module to `sys.modules`, so stuff gets cleaned up automatically as it leaves scope. In fastplotlib,`importlib.import_module()` is used, but I see no logic that removes the module from `sys.modules`, so its indeed expected that everything stays alive :)

**Comment by kushalkolar** [comment]
Thanks! We'll try this, I think @clewis7 made out `test_examples` based on the pygfx one from a year or more ago.

**Comment by kushalkolar** [comment]
Thanks @almarklein ! Using `import_from_path()` definitely helped a lot, max RAM usage when building locally was ~1.25GB but that's still too much for RTD apparently :man_shrugging: . Just going to move to something else.

**Comment by kushalkolar** [comment]
fixed, we used the cleanup approach with `import_from_path()` but alas it wasn't enough for RTD so we're hosting the docs ourselves now, done in #639
