### ISSUE TITLE
Use github actions to deploy to rtd

### ISSUE THREAD

**Issue by kushalkolar** [fastplotlib/fastplotlib#628]
This is interesting, maybe we can use github actions to build the rtd build and then host on rtd: https://github.com/dfm/rtds-action

if the RAM issues are still being a persistent problem

**Comment by clewis7** [comment]
There is also an idea that I think the data scientists are moving more toward which is for the project to have its own website and then the docs be a link off the main website

I am not sure though if they are still going to be hosting their docs using rtd or not

**Comment by kushalkolar** [comment]
done in #639
