### ISSUE TITLE
Limited control of axes on LineGraphics, can't display data with small scales

### ISSUE THREAD

**Issue by FlynnOConnell** [fastplotlib/fastplotlib#684]
Line Graphic objects aren't displaying properly due to high ymin/ymax values even when the axis scale should be low. 

The below sample data is a frame-by-frame correlation for the first 200 frames. 

## Sample data

[frame_correlations_200_frames.csv](https://github.com/user-attachments/files/18155467/frame_correlations_200_frames.csv)

```python
import numpy as np

data_path = './frame_correlations_200_frames.csv'
correlations = np.loadtxt(path, delimiter=',')
correlations.shape
>>> (200,)
print(correlations.min(), correlations.max())
>>> (0.7674947330073129, 0.7980724664391188)
```
## matplotlib result:

```python
import matplotlib.pyplot as plt

plt.plot(correlations)
```

![corr](https://github.com/user-attachments/assets/bea4fb42-1617-4a10-b75e-217414e8226a)

## fastplotlib result

```python
import fastplotlib as fpl
figure = fpl.Figure()  # figure_kwargs 'size' doesn't help

# no obvious arguments to add_line to control either axis
corr_graphic = figure[0, 0].add_line(data=correlations)
subplot = figure[0,0]
figure.show()
```

![fastplotlib_result](https://github.com/user-attachments/assets/c4b210ff-518f-4614-8dbd-ec8a844e55c7)

Zooming into the line eventually causes the line to disappear. Adding visible axes doesn't change this behavior, and it not clear from the documentation that there is a direct way to do this. 

Thanks :)

**Comment by kushalkolar** [comment]
this works fine, you just need to not maintain the aspect ratio of the camera, `subplot.camera.maintain_aspect = False`, click the toolbar button, or when you show the figure `fig.show(maintain_aspect=False)`

**Comment by FlynnOConnell** [comment]
Perfect!

![corr_aspect](https://github.com/user-attachments/assets/17285fb1-19bb-40b1-b21c-30b3dab7f57c)

**Comment by FlynnOConnell** [comment]
Perfect!

![corr_aspect](https://github.com/user-attachments/assets/092e09d7-d441-4801-b434-4047177b792c)
