### ISSUE TITLE
Add support for visualizing real time 1D/2D data via buffers

### ISSUE THREAD

**Issue by ArjunPutcha** [fastplotlib/fastplotlib#82]
Two types of buffer

- Static Buffer w/ Replacement (Rolling Buffer): collections.deque
- Static Buffer w/out Replacement: set alpha=0 for 'future' timepoints

**Comment by kushalkolar** [comment]
For "rolling buffer" we'd need to profile how fast it is, a simple approach could be:

With just fancy indexing:
```python3
# shift all points to the left by 1
geometry.positions.data[:-1] = `geometry.positions.data[1:]

# add new point to the end
geometry.positions.data[-1] = new_streamed_point
```

We could implement a `n_min_shift` size where the shift only occurs when `n_min_shift` new points are available.

We could also look at  [np.roll()](https://numpy.org/doc/stable/reference/generated/numpy.roll.html) and see how it performs compared to just fancy indexing.
